# #!/bin/bash

# # Define the state codes and their corresponding loc_id in a simple array
# state_codes=("AL" "AK" "AZ" "AR" "CA" "CO" "CT" "DE" "FL" "GA" "HI" "ID" "IL" "IN" "IA" "KS" "KY" "LA" "ME" "MD" "MA" "MI" "MN" "MS" "MO" "MT" "NE" "NV" "NH" "NJ" "NM" "NY" "NC" "ND" "OH" "OK" "OR" "PA" "RI" "SC" "SD" "TN" "TX" "UT" "VT" "VA" "WA" "WV" "WI" "WY")

# # Function to get loc_id from state code
# get_loc_id() {
#     local state_code="$1"
#     for i in "${!state_codes[@]}"; do
#         if [[ "${state_codes[$i]}" == "$state_code" ]]; then
#             echo $((i + 1))
#             return
#         fi
#     done
#     echo "0"  # Return 0 if not found
# }

# # Define the input data
# input_data=(
#     "Birmingham Civil Rights|AL"
# "Freedom Riders|AL"
# "Horseshoe Bend|Daviston, AL"
# "Little River Canyon|Fort Payne, AL"
# "Natchez Trace|the states of AL,MS,TN"
# "Natchez Trace|Tupelo, AL,MS,TN"
# "Russell Cave|Bridgeport, AL"
# "Selma To Montgomery|Montgomery, Lowndes & Dallas Counties, AL"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Tuskegee Airmen|Tuskegee, AL"
# "Tuskegee Institute|Tuskegee Institute, AL"
# "Alagnak|King Salmon, AK"
# "Alaska Public Lands|Anchorage, AK"
# "Aleutian Islands World War II|Unalaska/Dutch Harbor, AK"
# "Aniakchak|King Salmon, AK"
# "Bering Land Bridge|Nome, AK"
# "Cape Krusenstern|Kotzebue, AK"
# "Denali|Denali Park, AK"
# "Gates Of The Arctic|Bettles, AK"
# "Glacier Bay|Gustavus, AK"
# "Iñupiat Heritage Center|Barrow , AK"
# "Katmai|King Salmon, AK"
# "Kenai Fjords|Seward, AK"
# "Klondike Gold Rush|Skagway, AK"
# "Kobuk Valley|Kotzebue, AK"
# "Lake Clark|Port Alsworth, AK"
# "Noatak|Kotzebue, AK"
# "Sitka|Sitka, AK"
# "Wrangell - St Elias|Copper Center, AK"
# "Yukon - Charley Rivers|Eagle, AK"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Canyon de Chelly|Chinle, AZ"
# "Casa Grande Ruins|Coolidge, AZ"
# "Chiricahua|Willcox, AZ"
# "Coronado|Hereford, AZ"
# "Fort Bowie|Willcox, AZ"
# "Glen Canyon|Glen Canyon National Recreation Area, AZ,UT"
# "Grand Canyon|Grand Canyon, AZ"
# "Grand Canyon-Parashant|Northern Arizona, AZ"
# "Hubbell Trading Post|Ganado, AZ"
# "Juan Bautista de Anza|Nogales, AZ to San Francisco, CA, AZ,CA"
# "Lake Mead|the Mojave Desert, AZ,NV"
# "Montezuma Castle|Camp Verde, AZ"
# "Navajo|Black Mesa, AZ"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Organ Pipe Cactus|Ajo, AZ"
# "Petrified Forest|Petrified Forest National Park, AZ"
# "Pipe Spring|Fredonia, AZ"
# "Saguaro|Tucson, AZ"
# "Sunset Crater Volcano|Flagstaff, AZ"
# "Tonto|Roosevelt, AZ"
# "Tumacácori|Tumacácori, AZ"
# "Tuzigoot|Clarkdale, AZ"
# "Walnut Canyon|Flagstaff, AZ"
# "Wupatki|Flagstaff, AZ"
# "Arkansas Post|Gillett, AR"
# "Buffalo|Harrison and St. Joe, AR"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Fort Smith|Fort Smith, AR,OK"
# "Hot Springs|Hot Springs, AR"
# "Little Rock Central High School|Little Rock, AR"
# "Pea Ridge|Pea Ridge, AR"
# "President William Jefferson Clinton Birthplace Home|Hope, AR"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Alcatraz Island|San Francisco, CA"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Cabrillo|San Diego, CA"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Castle Mountains|Barstow, CA"
# "César E. Chávez|CA"
# "Channel Islands|Ventura, CA"
# "Death Valley|Death Valley, CA,NV"
# "Devils Postpile|the Sierra Nevada near Mammoth Lakes, CA"
# "Eugene O'Neill|Danville, CA"
# "Fort Point|Presidio of San Francisco, CA"
# "Golden Gate|San Francisco, CA"
# "John Muir|Martinez, CA"
# "Joshua Tree|Southern California between I-10 and Hwy 62; headquarters in Twentynine Palms, CA"
# "Juan Bautista de Anza|Nogales, AZ to San Francisco, CA, AZ,CA"
# "Lassen Volcanic|Mineral, CA"
# "Lava Beds|Tulelake, CA"
# "Manzanar|Independence, CA"
# "Mojave|Southern California between I-15 and I-40; headquarters in Barstow, CA"
# "Muir Woods|Mill Valley, CA"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Pinnacles|Paicines, CA"
# "Point Reyes|Point Reyes, CA"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Port Chicago Naval Magazine|Concord Naval Weapons Station, CA"
# "Presidio of San Francisco|San Francisco, CA"
# "Redwood|Del Norte & Humboldt counties , CA"
# "Rosie the Riveter WWII Home Front|Richmond, CA"
# "San Francisco Maritime|San Francisco, CA"
# "Santa Monica Mountains|Thousand Oaks, CA"
# "Sequoia & Kings Canyon|In the southern Sierra Nevada in Tulare and Fresno counties, CA"
# "Tule Lake|Tulelake, CA"
# "Whiskeytown|Whiskeytown, CA"
# "Yosemite|the Sierra Nevada, CA"
# "Amache|"
# "Bent's Old Fort|La Junta, CO"
# "Black Canyon Of The Gunnison|Montrose, CO"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Colorado|Fruita, CO"
# "Curecanti|Gunnison, CO"
# "Dinosaur|Vernal, Utah & Dinosaur, Colorado, CO,UT"
# "Florissant Fossil Beds|Florissant, CO"
# "Great Sand Dunes|Mosca, CO"
# "Hovenweep|Blanding, Utah & Cortez, Colorado, CO,UT"
# "Mesa Verde|Cortez and Mancos, CO"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Rocky Mountain|Estes Park and Grand Lake, CO"
# "Sand Creek Massacre|Kiowa County, CO"
# "Santa Fe|CO,KS,MO,NM,OK"
# "Yucca House|Cortez, CO"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Coltsville|Hartford, CT"
# "New England|MA,CT"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Weir Farm|Ridgefield & Wilton, CT"
# "Captain John Smith Chesapeake|Various States VA,MD,DE,DC,PA,NY"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "First State|DE,PA"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Big Cypress|Ochopee, FL"
# "Biscayne|Miami, Key Biscayne & Homestead, FL"
# "Canaveral|Titusville and New Smyrna Beach, FL"
# "Castillo de San Marcos|St. Augustine, FL"
# "De Soto|Bradenton, FL"
# "Dry Tortugas|Key West, FL"
# "Everglades|Miami, Naples, and Homestead, FL"
# "Fort Caroline|the Timucuan Preserve; Jacksonville, FL"
# "Fort Matanzas|St. Augustine, FL"
# "Gulf Islands|Gulf Breeze, Florida and Ocean Springs, Mississippi , FL,MS"
# "Timucuan|Jacksonville, FL"
# "Andersonville|Andersonville, GA"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Chattahoochee River|Atlanta, GA"
# "Chickamauga & Chattanooga|Fort Oglethorpe, GA,TN"
# "Cumberland Island|Saint Marys, GA"
# "Fort Frederica|St. Simons Island, GA"
# "Fort Pulaski|Savannah, GA"
# "Jimmy Carter|Plains, GA"
# "Kennesaw Mountain|Kennesaw, GA"
# "Martin Luther King, Jr.|Atlanta, GA"
# "Ocmulgee Mounds|Macon, GA"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Ala Kahakai|the Island of Hawaii, HI"
# "Haleakalā|Kula, Maui, HI"
# "Hawaiʻi Volcanoes|Hilo, HI"
# "Honouliuli|HI"
# "Kalaupapa|Kalaupapa, HI"
# "Kaloko-Honokōhau|Kailua-Kona, HI"
# "Pearl Harbor|Honolulu, HI"
# "Puʻuhonua o Hōnaunau|Honaunau, HI"
# "Puʻukoholā Heiau|Kawaihae, HI"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "City Of Rocks|Almo, ID"
# "Craters Of The Moon|Arco, Carey and Rupert , ID"
# "Hagerman Fossil Beds|Hagerman, ID"
# "Ice Age Floods|WA,OR,ID,MT"
# "Lewis & Clark|Sixteen States"
# "Minidoka|Jerome, ID,WA"
# "Nez Perce|four states ID,MT,OR,WA"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Yellowstone|Yellowstone National Park, ID,MT,WY"
# "Emmett Till and Mamie Till-Mobley|IL,MS"
# "Lewis & Clark|Sixteen States"
# "Lincoln Home|Springfield, IL"
# "Mormon Pioneer|Various States IL,IA,NE,UT,WY"
# "New Philadelphia|IL"
# "Pullman|Chicago, IL"
# "Springfield 1908 Race Riot|IL"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "George Rogers Clark|Vincennes, IN"
# "Indiana Dunes|Porter, IN"
# "Lewis & Clark|Sixteen States"
# "Lincoln Boyhood|Lincoln City, IN"
# "Effigy Mounds|Harpers Ferry, IA"
# "Herbert Hoover|West Branch, IA"
# "Lewis & Clark|Sixteen States"
# "Mormon Pioneer|Various States IL,IA,NE,UT,WY"
# "Brown v. Board of Education|Topeka, KS"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Fort Larned|Larned, KS"
# "Fort Scott|Fort Scott, KS"
# "Lewis & Clark|Sixteen States"
# "Nicodemus|Nicodemus, KS"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Santa Fe|CO,KS,MO,NM,OK"
# "Tallgrass Prairie|Strong City, KS"
# "Abraham Lincoln Birthplace|Hodgenville, KY"
# "Big South Fork|Oneida, KY,TN"
# "Camp Nelson|KY"
# "Cumberland Gap|Middlesboro, KY,TN,VA"
# "Fort Donelson|Dover, KY,TN"
# "Lewis & Clark|Sixteen States"
# "Mammoth Cave|Mammoth Cave, KY"
# "Mill Springs Battlefield|KY"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Cane River Creole|Natchez, LA"
# "El Camino Real de los Tejas|Various States TX,LA"
# "Jean Lafitte|New Orleans, LA"
# "New Orleans Jazz|New Orleans, LA"
# "Poverty Point|Epps, LA"
# "Vicksburg|Vicksburg, MS,LA"
# "Acadia|Bar Harbor, ME"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Katahdin Woods and Waters|ME"
# "Maine Acadian Culture|St. John Valley, ME"
# "Roosevelt Campobello|Lubec , ME"
# "Saint Croix Island|Calais, ME"
# "Antietam|Sharpsburg, MD"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Assateague Island|MD,VA"
# "Baltimore-Washington|Washington D.C. and Baltimore, Maryland, MD"
# "Captain John Smith Chesapeake|Various States VA,MD,DE,DC,PA,NY"
# "Catoctin Mountain|Thurmont, MD"
# "Chesapeake & Ohio Canal|Potomac River, DC,MD,WV"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "Civil War Defenses of Washington|Washington, DC,MD,VA"
# "Clara Barton|Glen Echo , MD"
# "Fort Foote|Oxon Hill, MD"
# "Fort McHenry|Baltimore, MD"
# "Fort Washington|Fort Washington, MD"
# "George Washington|DC,MD,VA"
# "Glen Echo|Glen Echo, MD"
# "Greenbelt|Greenbelt, MD"
# "Hampton|Towson, MD"
# "Harmony Hall|Prince George's County, MD"
# "Harpers Ferry|Harpers Ferry, WV,VA,MD"
# "Harriet Tubman Underground Railroad|Cambridge, MD"
# "Monocacy|Frederick, MD"
# "Oxon Cove Park & Oxon Hill Farm|Oxon Hill, MD"
# "Piscataway|Accokeek., MD"
# "Potomac Heritage|the corridor between the Chesapeake Bay and the Allegheny Highlands, DC,MD,PA,VA"
# "Star-Spangled Banner|DC,MD,VA"
# "Thomas Stone|Port Tobacco, MD"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Adams|Quincy, MA"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Blackstone River Valley|RI,MA"
# "Boston|Boston, MA"
# "Boston African American|Boston, MA"
# "Boston Harbor Islands|Boston, MA"
# "Cape Cod|Wellfleet, MA"
# "Frederick Law Olmsted|Brookline, MA"
# "John Fitzgerald Kennedy|Brookline, MA"
# "Longfellow House Washington's Headquarters|Cambridge, MA"
# "Lowell|Lowell, MA"
# "Minute Man|Concord, Lincoln, Lexington, MA"
# "New Bedford Whaling|New Bedford, MA"
# "New England|MA,CT"
# "Salem Maritime|Salem, MA"
# "Saugus Iron Works|Saugus, MA"
# "Springfield Armory|Springfield, MA"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Isle Royale|Houghton, MI"
# "Keweenaw|Calumet, MI"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Pictured Rocks|Munising, Grand Marais, MI"
# "River Raisin|MI"
# "Sleeping Bear Dunes|Empire, MI"
# "Grand Portage|Grand Portage, MN"
# "Mississippi|Twin Cities Metropolitan Area, MN"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Pipestone|Pipestone, MN"
# "Saint Croix|Saint Croix Falls, WI,MN"
# "Voyageurs|International Falls, Kabetogama, Ash River, and Crane Lake, MN"
# "Brices Cross Roads|Baldwyn, MS"
# "Emmett Till and Mamie Till-Mobley|IL,MS"
# "Gulf Islands|Gulf Breeze, Florida and Ocean Springs, Mississippi , FL,MS"
# "Medgar and Myrlie Evers Home|MS"
# "Natchez|Natchez, MS"
# "Natchez Trace|the states of AL,MS,TN"
# "Natchez Trace|Tupelo, AL,MS,TN"
# "Shiloh|Shiloh, TN,MS"
# "Tupelo|Tupelo, MS"
# "Vicksburg|Vicksburg, MS,LA"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Gateway Arch|St. Louis, MO"
# "George Washington Carver|Diamond, MO"
# "Harry S Truman|Independence and Grandview, MO"
# "Lewis & Clark|Sixteen States"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Ozark|Van Buren,Eminence,Salem,Winona, MO"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Santa Fe|CO,KS,MO,NM,OK"
# "Ste. Geneviève|MO"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Ulysses S Grant|St. Louis, MO"
# "Wilson's Creek|Republic, MO"
# "Big Hole|Wisdom, MT"
# "Bighorn Canyon|Fort Smith, MT,WY"
# "Fort Union Trading Post|Two States"
# "Glacier|Northwest Montana, MT"
# "Grant-Kohrs Ranch|Deer Lodge, MT"
# "Ice Age Floods|WA,OR,ID,MT"
# "Lewis & Clark|Sixteen States"
# "Little Bighorn Battlefield|Crow Agency, MT"
# "Nez Perce|four states ID,MT,OR,WA"
# "Yellowstone|Yellowstone National Park, ID,MT,WY"
# "Agate Fossil Beds|Harrison, NE"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Homestead|Beatrice, NE"
# "Lewis & Clark|Sixteen States"
# "Missouri|Yankton, SD,NE"
# "Mormon Pioneer|Various States IL,IA,NE,UT,WY"
# "Niobrara|Valentine, NE"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Scotts Bluff|Gering, NE"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Death Valley|Death Valley, CA,NV"
# "Great Basin|Baker, NV"
# "Lake Mead|the Mojave Desert, AZ,NV"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Tule Springs Fossil Beds|NV"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Saint-Gaudens|Cornish, NH"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Delaware Water Gap|HQ in Bushkill PA; the park is along the Delaware River in the states of NJ,PA"
# "Ellis Island|NJ,NY"
# "Gateway|Brooklyn, Queens & Staten Island, New York and Monmouth County, New Jersey, NY,NJ"
# "Great Egg Harbor River|NJ"
# "Lower Delaware|PA,NJ"
# "Morristown|Morristown, NJ"
# "New Jersey Pinelands|Southeastern New Jersey, NJ"
# "Paterson Great Falls|Paterson, NJ"
# "Thomas Edison|West Orange, NJ"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Aztec Ruins|Aztec, NM"
# "Bandelier|Los Alamos, NM"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Capulin Volcano|Capulin, NM"
# "Carlsbad Caverns|Carlsbad, NM"
# "Chaco Culture|Nageezi, NM"
# "El Camino Real de Tierra Adentro|NM,TX"
# "El Malpais|Grants, NM"
# "El Morro|Ramah, NM"
# "Fort Union|Watrous, NM"
# "Gila Cliff Dwellings|Silver City, NM"
# "Manhattan Project|Manhattan Project National Historical Park, NM,WA,TN"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Pecos|Pecos, NM"
# "Petroglyph|Albuquerque, NM"
# "Salinas Pueblo Missions|Mountainair, NM"
# "Santa Fe|CO,KS,MO,NM,OK"
# "Valles Caldera|Jemez Springs, NM"
# "White Sands|Alamogordo, NM"
# "African Burial Ground|NY"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Captain John Smith Chesapeake|Various States VA,MD,DE,DC,PA,NY"
# "Castle Clinton|New York, NY"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "Eleanor Roosevelt|Hyde Park, NY"
# "Ellis Island|NJ,NY"
# "Federal Hall|New York, NY"
# "Fire Island|Patchogue, NY"
# "Fort Stanwix|Rome, NY"
# "Gateway|Brooklyn, Queens & Staten Island, New York and Monmouth County, New Jersey, NY,NJ"
# "General Grant|New York, NY"
# "Governors Island|New York, NY"
# "Hamilton Grange|New York, NY"
# "Harriet Tubman|Auburn, NY"
# "Home Of Franklin D Roosevelt|Hyde Park, NY"
# "Lower East Side Tenement Museum|Manhattan, NY"
# "Martin Van Buren|Kinderhook, NY"
# "National Parks of New York Harbor|Northern New Jersey and New York City, NY"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Sagamore Hill|Oyster Bay, NY"
# "Saint Paul's Church|Mount Vernon, NY - 897 South Columbus Avenue, NY"
# "Saratoga|Stillwater, NY"
# "Statue Of Liberty|Ellis Island, NY"
# "Stonewall|NY"
# "Theodore Roosevelt Birthplace|New York, NY"
# "Theodore Roosevelt Inaugural|Buffalo, NY"
# "Thomas Cole|Catskill, NY"
# "Upper Delaware|Pike and Wayne (PA) and Delaware, Orange and Sullivan (NY) counties along the Delaware River, NY,PA"
# "Vanderbilt Mansion|Hyde Park, NY"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Women's Rights|Seneca Falls, NY"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Blue Ridge|Blue Ridge Mountains of Virginia and North Carolina, NC,VA"
# "Cape Hatteras|Nags Head, Buxton, Ocracoke, NC"
# "Cape Lookout|Harkers Island, NC"
# "Carl Sandburg Home|Flat Rock, NC"
# "Fort Raleigh|Manteo, NC"
# "Great Smoky Mountains|the states of NC,TN"
# "Guilford Courthouse|Greensboro, NC"
# "Moores Creek|Currie, NC"
# "Overmountain Victory|NC,SC,TN,VA"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Wright Brothers|Kill Devil Hills, NC"
# "Fort Union Trading Post|Two States"
# "Knife River Indian Villages|Stanton, ND"
# "Lewis & Clark|Sixteen States"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Theodore Roosevelt|Medora, ND (South Unit). The North Unit is located 15 miles south of Watford City, ND"
# "Charles Young Buffalo Soldiers|Xenia, OH"
# "Cuyahoga Valley|Cleveland and Akron, OH"
# "Dayton Aviation Heritage|Dayton, OH"
# "First Ladies|Canton, OH"
# "Hopewell Culture|Chillicothe, OH"
# "James A Garfield|Mentor, OH"
# "Lewis & Clark|Sixteen States"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Perry's Victory & International Peace|Put-in-Bay, OH"
# "William Howard Taft|Cincinnati, OH"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Chickasaw|Sulphur, OK"
# "Fort Smith|Fort Smith, AR,OK"
# "Oklahoma City|Oklahoma City, OK"
# "Santa Fe|CO,KS,MO,NM,OK"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Washita Battlefield|Cheyenne, OK"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Crater Lake|Crater Lake, OR"
# "Fort Vancouver|Vancouver, OR,WA"
# "Ice Age Floods|WA,OR,ID,MT"
# "John Day Fossil Beds|Kimberly, OR"
# "Lewis & Clark|Sixteen States"
# "Lewis and Clark|Long Beach to Cannon Beach, OR,WA"
# "Nez Perce|four states ID,MT,OR,WA"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Oregon Caves|Cave Junction, OR"
# "Allegheny Portage Railroad|Gallitzin, PA"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Captain John Smith Chesapeake|Various States VA,MD,DE,DC,PA,NY"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "Delaware Water Gap|HQ in Bushkill PA; the park is along the Delaware River in the states of NJ,PA"
# "Edgar Allan Poe|Philadelphia, PA"
# "Eisenhower|Gettysburg, PA"
# "First State|DE,PA"
# "Flight 93|Shanksville, PA"
# "Fort Necessity|Farmington, PA"
# "Friendship Hill|Point Marion, PA"
# "Gettysburg|Gettysburg, PA"
# "Gloria Dei Church|Philadelphia, PA"
# "Hopewell Furnace|Elverson, PA"
# "Independence|Philadelphia, PA"
# "Johnstown Flood|South Fork, PA"
# "Lewis & Clark|Sixteen States"
# "Lower Delaware|PA,NJ"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Potomac Heritage|the corridor between the Chesapeake Bay and the Allegheny Highlands, DC,MD,PA,VA"
# "Steamtown|Scranton, PA"
# "Thaddeus Kosciuszko|Philadelphia, PA"
# "Upper Delaware|Pike and Wayne (PA) and Delaware, Orange and Sullivan (NY) counties along the Delaware River, NY,PA"
# "Valley Forge|Valley Forge, PA"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Blackstone River Valley|RI,MA"
# "Roger Williams|Providence, RI"
# "Touro Synagogue|Newport, RI"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Charles Pinckney|Mt. Pleasant, SC"
# "Congaree|Hopkins, SC"
# "Cowpens|Chesnee, SC"
# "Fort Sumter and Fort Moultrie|Charleston Harbor, SC"
# "Kings Mountain|Blacksburg, SC"
# "Ninety Six|Ninety Six, SC"
# "Overmountain Victory|NC,SC,TN,VA"
# "Reconstruction Era|SC"
# "Badlands|Southwestern, SD"
# "Jewel Cave|Custer, SD"
# "Lewis & Clark|Sixteen States"
# "Minuteman Missile|Southwestern , SD"
# "Missouri|Yankton, SD,NE"
# "Mount Rushmore|Keystone, SD"
# "Wind Cave|Hot Springs, SD"
# "Andrew Johnson|Greeneville, TN"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Big South Fork|Oneida, KY,TN"
# "Chickamauga & Chattanooga|Fort Oglethorpe, GA,TN"
# "Cumberland Gap|Middlesboro, KY,TN,VA"
# "Fort Donelson|Dover, KY,TN"
# "Great Smoky Mountains|the states of NC,TN"
# "Manhattan Project|Manhattan Project National Historical Park, NM,WA,TN"
# "Natchez Trace|the states of AL,MS,TN"
# "Natchez Trace|Tupelo, AL,MS,TN"
# "Obed|Wartburg, TN"
# "Overmountain Victory|NC,SC,TN,VA"
# "Shiloh|Shiloh, TN,MS"
# "Stones River|Murfreesboro, TN"
# "Trail Of Tears|AL,AR,GA,IL,KY,MO,NC,OK,TN"
# "Alibates Flint Quarries|Fritch, TX"
# "Amistad|Del Rio, TX"
# "Big Bend|The big bend of the Rio Grande, TX"
# "Big Thicket|Beaumont, TX"
# "Blackwell School|TX"
# "Butterfield Overland|MO, AR, OK, TX, NM, AZ, CA"
# "Chamizal|El Paso, TX"
# "El Camino Real de los Tejas|Various States TX,LA"
# "El Camino Real de Tierra Adentro|NM,TX"
# "Fort Davis|Fort Davis, TX"
# "Guadalupe Mountains|Salt Flat, TX"
# "Lake Meredith|Fritch, TX"
# "Lyndon B Johnson|Johnson City, TX"
# "Padre Island|Corpus Christi, TX"
# "Palo Alto Battlefield|Brownsville, TX"
# "Rio Grande|Southwest Texas, TX"
# "San Antonio Missions|San Antonio, TX"
# "Waco Mammoth|Waco, TX"
# "Arches|Moab, UT"
# "Bryce Canyon|Bryce Canyon, UT"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Canyonlands|Moab, UT"
# "Capitol Reef|Torrey, UT"
# "Cedar Breaks|Cedar City, UT"
# "Dinosaur|Vernal, Utah & Dinosaur, Colorado, CO,UT"
# "Glen Canyon|Glen Canyon National Recreation Area, AZ,UT"
# "Golden Spike|Brigham City, UT"
# "Hovenweep|Blanding, Utah & Cortez, Colorado, CO,UT"
# "Mormon Pioneer|Various States IL,IA,NE,UT,WY"
# "Natural Bridges|Blanding, UT"
# "Old Spanish|AZ,CA,CO,NV,NM,UT"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Rainbow Bridge|Rainbow Bridge National Monument, UT"
# "Timpanogos Cave|American Fork, UT"
# "Zion|Springdale, UT"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Marsh - Billings - Rockefeller|Woodstock, VT"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Appomattox Court House|Appomattox, VA"
# "Arlington House, The Robert E. Lee Memorial|Arlington, VA"
# "Assateague Island|MD,VA"
# "Blue Ridge|Blue Ridge Mountains of Virginia and North Carolina, NC,VA"
# "Booker T Washington|Hardy, VA"
# "Cape Henry Memorial|Fort Story, VA"
# "Captain John Smith Chesapeake|Various States VA,MD,DE,DC,PA,NY"
# "Cedar Creek & Belle Grove|Middletown and Strasburg, VA"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "Civil War Defenses of Washington|Washington, DC,MD,VA"
# "Colonial|Jamestown and Yorktown, VA"
# "Cumberland Gap|Middlesboro, KY,TN,VA"
# "Fort Monroe|Fort Monroe, VA"
# "Fredericksburg & Spotsylvania|Fredericksburg, VA"
# "George Washington|DC,MD,VA"
# "George Washington Birthplace|Westmoreland County, VA"
# "Great Falls|McLean, VA"
# "Green Springs|Louisa County, VA"
# "Harpers Ferry|Harpers Ferry, WV,VA,MD"
# "Historic Jamestowne|James City County, VA"
# "Maggie L Walker|Richmond, VA"
# "Manassas|Manassas, VA"
# "Overmountain Victory|NC,SC,TN,VA"
# "Petersburg|Petersburg, VA"
# "Potomac Heritage|the corridor between the Chesapeake Bay and the Allegheny Highlands, DC,MD,PA,VA"
# "Prince William Forest|Triangle, VA"
# "Richmond|Richmond, VA"
# "Shenandoah|the Blue Ridge Mountains near Luray, VA"
# "Star-Spangled Banner|DC,MD,VA"
# "Washington-Rochambeau Revolutionary Route|MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"
# "Wolf Trap National Park for the Performing Arts|Vienna, VA"
# "Yorktown Battlefield|Yorktown, VA"
# "Ebey's Landing|Coupeville, WA"
# "Fort Vancouver|Vancouver, OR,WA"
# "Ice Age Floods|WA,OR,ID,MT"
# "Klondike Gold Rush - Seattle Unit|Seattle, WA"
# "Lake Roosevelt|the Canadian border going to Coulee Dam along the Columbia River, WA"
# "Lewis & Clark|Sixteen States"
# "Lewis and Clark|Long Beach to Cannon Beach, OR,WA"
# "Manhattan Project|Manhattan Project National Historical Park, NM,WA,TN"
# "Minidoka|Jerome, ID,WA"
# "Mount Rainier|Ashford, Enumclaw, Packwood, Wilkeson, WA"
# "Nez Perce|four states ID,MT,OR,WA"
# "North Cascades|Marblemount, WA"
# "Olympic|Port Angeles, WA"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "San Juan Island|Friday Harbor, WA"
# "Whitman Mission|Walla Walla, WA"
# "Wing Luke Museum|Seattle, WA"
# "Appalachian|Maine to Georgia, CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"
# "Bluestone|Athens, Pipestem, and Hinton, WV"
# "Chesapeake & Ohio Canal|Potomac River, DC,MD,WV"
# "Chesapeake Bay|Chesapeake Bay Watershed, DC,DE,MD,NY,PA,VA,WV"
# "Gauley River|Summersville, WV"
# "Harpers Ferry|Harpers Ferry, WV,VA,MD"
# "Lewis & Clark|Sixteen States"
# "New River Gorge|Hinton, Beckley, Glen Jean, and Fayetteville, WV"
# "Apostle Islands|Lake Superior, WI"
# "Ice Age|Madison, WI"
# "North Country|Eight States - Vermont to North Dakota MI,MN,ND,NY,OH,PA,VT,WI"
# "Saint Croix|Saint Croix Falls, WI,MN"
# "Bighorn Canyon|Fort Smith, MT,WY"
# "California|Various States CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"
# "Devils Tower|Devils Tower, WY"
# "Fort Laramie|Southeast Wyoming, WY"
# "Fossil Butte|Kemmerer, WY"
# "Grand Teton|Moose, WY"
# "Mormon Pioneer|Various States IL,IA,NE,UT,WY"
# "Oregon|Various States ID,KS,MO,NE,OR,WA,WY"
# "Pony Express|Various States CA,CO,KS,MO,NE,NV,UT,WY"
# "Yellowstone|Yellowstone National Park, ID,MT,WY"
# # Add more entries as needed
# )

# # Generate SQL insert statements
# for entry in "${input_data[@]}"; do
#     IFS='|' read -r name states <<< "$entry"
    
#     # Extract valid state codes by checking against the known list
#     extracted_state_codes=()
#     for code in "${state_codes[@]}"; do
#         if [[ "$states" == *"$code"* ]]; then
#             extracted_state_codes+=("$code")
#         fi
#     done
    
#     # Use the first extracted state code to get loc_id
#     if [ ${#extracted_state_codes[@]} -gt 0 ]; then
#         first_state="${extracted_state_codes[0]}"
#         loc_id=$(get_loc_id "$first_state")
        
#         if [ "$loc_id" -eq 0 ]; then
#             echo "Error: Invalid state code '$first_state' for entry '$entry'."
#         else
#             # Output the SQL insert statement
#             echo "INSERT INTO national_park (name, loc_id) VALUES ('$name', $loc_id);"
#         fi
#     else
#         echo "Error: No valid state codes found for entry '$entry'."
#     fi
# done
